In [1]:
import numpy as np

## 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
dice_roll = ([1,2,3,4,5,6])
dice_trials = 2
dice_simulation = 1_000_000
two_dice = np.random.choice(dice_roll,(dice_simulation, dice_trials))

In [3]:
dub_chance = ((((two_dice == 1).sum(axis=1)) == 2)|(
    ((two_dice == 2).sum(axis=1)) == 2)|(
    ((two_dice == 3).sum(axis=1)) == 2)|(
    ((two_dice == 4).sum(axis=1) == 2)|(
    ((two_dice == 5).sum(axis=1) == 2)|(
    ((two_dice == 6).sum(axis=1) == 2))))).sum() / len(two_dice)
round(dub_chance*100,2)

16.69

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [4]:
coin_flip = ['H','T']
coin_trials = 8
coin_simulation = 1_000_000
eight_flips = np.random.choice(coin_flip,(coin_simulation, coin_trials))

In [5]:
(eight_flips == 'H').sum(axis=1)

array([5, 3, 6, ..., 6, 6, 4])

In [6]:
round(((eight_flips == 'H').sum(axis=1) ==3).sum() / len(eight_flips)*100,2)

21.9

### a. What is the probability of getting more than 3 heads?

In [7]:
round(((eight_flips == 'H').sum(axis=1) > 3).sum() / len(eight_flips)*100,2)

63.65

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [8]:
cohort_type = ['WD','WD','WD','DS']
bill_trials = 2
bill_sim = 1_000_000
chance_of_bill = np.random.choice(cohort_type,(bill_sim, bill_trials))

In [9]:
(chance_of_bill == 'DS').sum(axis=1)

array([0, 1, 0, ..., 0, 0, 1])

In [10]:
round(((chance_of_bill == 'DS').sum(axis=1) == 2).sum() / len(chance_of_bill)*100,2)

6.27

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [11]:
mean_pop = 3
std_pop = 1.5
simulated_pop = 1_000_000
pop_trial = 5
can_i_buy = np.random.normal(mean_pop, std_pop, size=(simulated_pop, pop_trial))

In [12]:
round(((can_i_buy.sum(axis=1) <= 16).mean())*100,2)

61.69

## 5. Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [13]:
np.random.normal?


Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 

In [14]:
men_height = np.random.normal(178,8,1_000_000)
women_height = np.random.normal(170,6,1_000_000)

In [15]:
round((women_height > men_height).sum()/len(women_height + men_height)*100,2)

21.22

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
### a. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [17]:
p_corrupt = .004
student_trials = 50
student_sims = 1_000_000
corrupt_chance = np.random.random((student_sims,student_trials))
corrupt_chance

array([[0.41343974, 0.42822056, 0.40272625, ..., 0.81423207, 0.81791679,
        0.01976793],
       [0.17106155, 0.98763406, 0.59295242, ..., 0.86248698, 0.63357056,
        0.53941967],
       [0.84672967, 0.15561818, 0.96312584, ..., 0.5483576 , 0.0637806 ,
        0.24198328],
       ...,
       [0.08618638, 0.7263591 , 0.79340954, ..., 0.773583  , 0.82203078,
        0.08718022],
       [0.56156597, 0.4852024 , 0.9172024 , ..., 0.73218216, 0.03597268,
        0.38883523],
       [0.69309653, 0.05616455, 0.22688031, ..., 0.11828617, 0.70319152,
        0.84523822]])

In [19]:
corruption = corrupt_chance < p_corrupt 
round(((corruption.sum(axis=1) == 0).mean())*100,2)

81.85

#### a. a. 100 students?

In [20]:
corrupt_chance_100 = np.random.random((student_sims,student_trials*2))
corruption_100 = corrupt_chance_100 < p_corrupt 
round(((corruption_100.sum(axis=1) == 0).mean())*100,2)

66.96

### b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [21]:
corrupt_chance_150 = np.random.random((student_sims,student_trials*3))
corruption_150 = corrupt_chance_150 < p_corrupt 
round(((corruption_150.sum(axis=1) >= 1).mean())*100,2)

45.24

### c. How likely is it that 450 students all download anaconda without an issue?

In [22]:
corrupt_chance_all = np.random.random((student_sims,student_trials*9))
corruption_all = corrupt_chance_all < p_corrupt 
round(((corruption_all.sum(axis=1) == 0).mean())*100,2)

16.46

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [23]:
#question rephrase
#how likely is it to see a food truck every day
p_food_truck = .7
days_without_food = 1
food_sims = 1_000_000
chance_of_food = np.random.random((food_sims,days_without_food*3))
chance_of_food

array([[0.8980204 , 0.83524161, 0.69167606],
       [0.16445452, 0.672135  , 0.6001105 ],
       [0.5463607 , 0.24126881, 0.1970015 ],
       ...,
       [0.11136254, 0.98009667, 0.29982801],
       [0.82594202, 0.63996481, 0.08180354],
       [0.88669388, 0.06315229, 0.36810408]])

In [24]:
food = chance_of_food < p_food_truck 
round(((food.sum(axis=1) == 0).mean())*100,2)

2.69

### a. How likely is it that a food truck will show up sometime this week?

In [25]:
chance_of_food_this_week = np.random.random((food_sims,days_without_food*7))
food_this_week = chance_of_food < p_food_truck 
round(((food.sum(axis=1) > 0).mean())*100,2)

97.31

## 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [26]:
possible_birth_dates = range(365)
people = 23
people_sims = 1_000_000
twinsies = np.random.choice(possible_birth_dates,(people_sims, people))
twinsies

array([[245, 196, 331, ..., 256,  20, 218],
       [ 27,  97, 151, ..., 162, 284, 276],
       [ 26, 172,   5, ...,  93, 213, 127],
       ...,
       [124, 191, 331, ..., 349, 359, 165],
       [231, 207,  40, ...,  46, 140,  53],
       [ 39, 317, 239, ..., 117, 304, 317]])

In [27]:
import pandas as pd
twinsies = pd.DataFrame(twinsies)
twinsies.head(1)

0    1    2   3    4    5    6    7    8   9   ...   13  14   15  16  17  \
0  245  196  331  31  333  168  252  150  177  27  ...  312  78  321  56  54   

    18   19   20  21   22  
0  104  186  256  20  218  

[1 rows x 23 columns]

In [28]:
round(((twinsies.nunique(axis=1) < 23).mean())*100,2)

50.78

### a. What if it's 20 people?

In [29]:
possible_birth_dates = range(365)
people = 20
people_sims = 1_000_000
twinsies = np.random.choice(possible_birth_dates,(people_sims, people))
twinsies = pd.DataFrame(twinsies)
twinsies.head(1)
round(((twinsies.nunique(axis=1) < people).mean())*100,2)

41.12

### b. 40?

In [30]:
possible_birth_dates = range(365)
people = 40
people_sims = 1_000_000
twinsies = np.random.choice(possible_birth_dates,(people_sims, people))
twinsies = pd.DataFrame(twinsies)
twinsies.head(1)
round(((twinsies.nunique(axis=1) < people).mean())*100,2)

89.16